# Generated by Django 5.0.2 on 2024-02-26 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorias_red_liceo', '0003_alter_documentomemoria_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentomemoria',
            name='referencia',
            field=models.IntegerField(),
        ),
    ]
