# Generated by Django 5.0.2 on 2024-02-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='recursos/libros/')),
                ('coordinadores', models.CharField(max_length=200, null=True)),
                ('ISBN', models.CharField(max_length=20, null=True)),
                ('fecha', models.DateField(null=True)),
                ('edicion', models.CharField(max_length=50, null=True)),
                ('autor', models.CharField(max_length=200, null=True)),
                ('fotoPortada', models.ImageField(blank=True, null=True, upload_to='recursos/fotos/')),
            ],
        ),
    ]
