# Generated by Django 5.0.2 on 2024-02-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidoPaterno', models.CharField(max_length=100)),
                ('apellidoMaterno', models.CharField(blank=True, max_length=100, null=True)),
                ('centroTrabajo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('education_degree', models.CharField(max_length=100)),
            ],
        ),
    ]
