# Generated by Django 5.0.2 on 2024-02-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembrored',
            name='apellidoMaterno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='miembrored',
            name='apellidoPaterno',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='miembrored',
            name='centroTrabajo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='miembrored',
            name='education_degree',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='miembrored',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
