# Generated by Django 5.0.2 on 2024-02-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LGC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='informacion',
            name='lgc',
        ),
        migrations.RemoveField(
            model_name='informacion',
            name='lgc_descripcion',
        ),
    ]
